
package com.example.restaurantmanagementapp;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;

// Import the generated View Binding class for your layout.
// The name is generated by converting the layout file name (activity_main.xml) to PascalCase and adding "Binding".
import com.example.restaurantmanagementapp.data.AppDatabase;
import com.example.restaurantmanagementapp.databinding.ActivityMainBinding;

public class MainActivity extends AppCompatActivity {

    // Declare the binding object.
    private ActivityMainBinding binding;
    private AppDatabase db;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // 1. Inflate the layout and initialize the binding object.
        binding = ActivityMainBinding.inflate(getLayoutInflater());

        // 2. Set the content view to the root of the binding.
        setContentView(binding.getRoot());

        // 3. Set up click listeners for the interactive elements (buttons, text).
        setupClickListeners();
    }

    private void setupClickListeners() {
        // Set a click listener for the Login button.
        binding.buttonLogin.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                handleLogin();
            }
        });

        // Set a click listener for the "Register" prompt text.
        binding.textRegisterPrompt.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                handleRegistration();
            }
        });

        // --- ADD THIS ---
        // Also set a click listener for the "Register" link itself.
        binding.textRegisterLink.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                handleRegistration();
            }
        });

        // --- ADD THIS ---
        // Add a click listener for the forgot password text.
        binding.textForgotPassword.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                // TODO: Navigate to your password recovery screen
                Toast.makeText(MainActivity.this, "Forgot Password clicked!", Toast.LENGTH_SHORT).show();
            }
        });
    }

    private void handleLogin() {
        String email = binding.editTextEmail.getText().toString().trim();
        String password = binding.editTextPassword.getText().toString().trim();

        if (email.isEmpty()) {
            binding.inputLayoutEmail.setError("Email is required");
            return;
        }
        if (password.isEmpty()) {
            binding.inputLayoutPassword.setError("Password is required");
            return;
        }

        // Check against Local DB
        AppDatabase db = AppDatabase.getDatabase(this);
        com.example.restaurantmanagementapp.data.User user = db.userDao().login(email, password);

        if (user != null) {
            Toast.makeText(this, "Welcome " + user.name, Toast.LENGTH_SHORT).show();
            navigateToDashboard(user.role);
        } else {
            Toast.makeText(this, "Invalid Credentials", Toast.LENGTH_SHORT).show();
        }
    }

    private void handleRegistration() {
        // For simplicity, we'll just create a dummy user or show a dialog.
        // In a real app, you'd have a separate RegisterActivity.
        // Here, we'll auto-register a Guest and a Staff user for testing if they don't
        // exist.

        AppDatabase db = AppDatabase.getDatabase(this);

        if (db.userDao().getUser("staff@test.com") == null) {
            db.userDao().insert(new com.example.restaurantmanagementapp.data.User("staff@test.com", "password", "STAFF",
                    "Staff Member"));
        }
        if (db.userDao().getUser("guest@test.com") == null) {
            db.userDao().insert(new com.example.restaurantmanagementapp.data.User("guest@test.com", "password", "GUEST",
                    "Guest User"));
        }

        Toast.makeText(this, "Test users created: staff@test.com / guest@test.com (password)", Toast.LENGTH_LONG)
                .show();
    }

    private void navigateToDashboard(String role) {

        Intent intent;
        if ("STAFF".equalsIgnoreCase(role)) {
            intent = new Intent(MainActivity.this, StaffDashboardActivity.class);
        } else {
            intent = new Intent(MainActivity.this, GuestDashboardActivity.class);
        }
        startActivity(intent);
        finish();
    }
}
